name: "Perform a code test"
description: "Installing dependenncies an running a test"

inputs:
   token:
     description: "Token needed to access files "
     required: true
   nested-install:
     description: "Patch to json file if it is in a folder"
     required: false
   nested-test:
     description: "Patch to test file if it is in a folder "
     required: false
   compile:
     description: "True if the code has to be compiled "
     required: false
runs:
   using: "composite"
   steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
        shell: bash
        run: |
          if [ -n "${{inputs.nested-install}}" ]; then
             cd ${{inputs.nested-install}}
             fi
          npm install
          if [ -n "${{inputs.compile}}" ]; then
             npm run compile
             fi
      - name: Run Tests
        shell: bash
        run: |
          if [ -n "${{inputs.nested-test}}" ]; then
              cd ${{inputs.nested-test}}
              fi
          npm run test
